# Generated by Django 3.2.4 on 2021-08-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='values',
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(default=1000000, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=1000000),
        ),
    ]
